<html>
	<head>
		<title>FMA::Family Memories App</title>
		<meta charset="utf-8">
		<meta http-equiv='X-UA-Compatible' content = 'IE=edge'/>
		<link rel="stylesheet" type="text/css" href="/css/commonUIStyle.css">
		<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	</head>
	<body>
		<div class="app-container" id="app-container">
			<div class="header-container">
				<div class="logo-header-container">
					<div class="gd-logo"></div>
					<div class="app-name"><a href="/">FMA</a></div></a>
					<div class="version">v 1.0</div>
					<div class="top-bar">
						<p>
						</p>
					</div>
				</div>
				<div class="menu-header clear-fix">
					<div class="right-content">
						<?php
							$userName = isset($user['first_name']) ? $user['first_name'] : '';
						?>
						<p>Welcome<br><?=$userName?>&nbsp<a href="<?=$loginoutLink?>"><?=!empty($userName)?'[Logout]':'[Login]'?></a>'</p>
					</div>
				</div>

				<div class='tabs clear-fix'>
					<ul id='tabNavigation' class='clear-fix'>
						<li class='activelink  ' id='NewsTab' onClick="window.location = 'index.php/news';"><span>News</span></li>
						<li class=' ' id='ImagesTab' onClick="window.location = 'index.php/images';"><span>Images</span></li>
						<li class=' ' id='VideosTab' onClick="window.location = 'index.php/videos';"><span>Videos</span></li>
						<li class=' ' id='AdminTab' onClick="window.location = 'index.php/admin';"><span>Admin</span></li>

					</ul>
				</div>			<div class="menu-area clear-fix">
					<div class="integrated-menu clear-fix" id="integrated_sub_menu">

						<ul id='subnav' class='nav'>

						</ul>
					</div>
				</div>
			</div>
			<div class="main_content_container">
				<?php $this->load->view($view_to_render, $variables_for_view); ?>
			</div>
			<div class="footer">Copyright &copy; kaiyansimmons.com - All rights reserved</div>
		</div>
	</body>
</html>